services:
  - type: web
    name: foto-xluz
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PIXELBIN_API_TOKEN
        sync: false   # la inserisci manualmente da dashboard
    autoDeploy: true
